# Generated by Django 2.2 on 2019-06-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('piece', models.IntegerField(default=1)),
                ('rate', models.IntegerField(default=0)),
            ],
        ),
    ]
