# Generated by Django 2.2 on 2019-06-18 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0002_auto_20190607_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=20, null=True)),
                ('street_area_locality', models.TextField(max_length=50)),
                ('state', models.CharField(max_length=25)),
                ('town_village_city', models.CharField(max_length=25)),
                ('pincode', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryBoyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=20, null=True)),
                ('street_area_locality', models.TextField(max_length=50)),
                ('state', models.CharField(max_length=25)),
                ('town_village_city', models.CharField(max_length=25)),
                ('pincode', models.DecimalField(decimal_places=0, max_digits=20)),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.DeliveryBoy')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=20, null=True)),
                ('street_area_locality', models.TextField(max_length=50)),
                ('state', models.CharField(max_length=25)),
                ('town_village_city', models.CharField(max_length=25)),
                ('pincode', models.DecimalField(decimal_places=0, max_digits=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Customer')),
            ],
        ),
    ]
