# Generated by Django 2.2 on 2019-06-26 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.DeliveryBoy'),
        ),
    ]
