# Generated by Django 2.2 on 2019-07-01 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20190626_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcomplition',
            name='duration_late',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
