# Generated by Django 2.2 on 2019-07-03 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20190701_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcount',
            name='request',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='request.Request'),
        ),
    ]
